# Generated by Django 4.2.7 on 2024-10-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('header_title', models.CharField(blank=True, max_length=255, null=True)),
                ('header_description', models.TextField(blank=True, null=True)),
                ('telegram_link', models.URLField(blank=True, max_length=255, null=True)),
                ('telegram_icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('instagram_link', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram_icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('whatsapp_link', models.URLField(blank=True, max_length=255, null=True)),
                ('whatsapp_icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
            ],
        ),
    ]
